### ISSUE TITLE
Change external IP address on HPC2

### ISSUE THREAD

**Issue by camillescott** [ucdavis/HPCCF-HPC2#7]
- Convert from netplan to /etc/network/interfaces (?) Necessary for pre-up for firewall?
    - `169.237.166.103/29`
    - Router: `169.237.166.110`
- Add firewall script
    - Templated from hpc1:
        - `/etc/ip.sh`
        - `/etc/iptables.sh`

**Comment by OmenWild** [comment]
Done, debugged, tested.
